//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerCommonLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Server {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Server() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerCommonLayer.Server", typeof(Server).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برقراري ارتباط با بانک اطلاعاتي مقدور نمي باشد.
        /// </summary>
        internal static string ecDBConnection {
            get {
                return ResourceManager.GetString("ecDBConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف گزينه مورد نظر وجود ندارد.
        /// </summary>
        internal static string ecDelete {
            get {
                return ResourceManager.GetString("ecDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکراري است.
        /// </summary>
        internal static string ecDuplicate {
            get {
                return ResourceManager.GetString("ecDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ویرایش گزینه مورد نظر وجود ندارد.
        /// </summary>
        internal static string ecEdit {
            get {
                return ResourceManager.GetString("ecEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخص نشده است.
        /// </summary>
        internal static string ecIncompelete {
            get {
                return ResourceManager.GetString("ecIncompelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معتبر نمی باشد.
        /// </summary>
        internal static string ecInvalid {
            get {
                return ResourceManager.GetString("ecInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این زمان قابلیت ثبت وجود ندارد.
        /// </summary>
        internal static string ecNotValidDate {
            get {
                return ResourceManager.GetString("ecNotValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستگاه بارکدخوان به سيستم متصل نيست و يا خاموش مي باشد.
        /// </summary>
        internal static string ecPDAConnectionError {
            get {
                return ResourceManager.GetString("ecPDAConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آيا مطمئن به حذف مي باشيد ؟.
        /// </summary>
        internal static string strDeleteWarning {
            get {
                return ResourceManager.GetString("strDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        internal static string strErrorTitle {
            get {
                return ResourceManager.GetString("strErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا تغییرات جاری ثبت گردد ؟.
        /// </summary>
        internal static string strPostWarning {
            get {
                return ResourceManager.GetString("strPostWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير سرور.
        /// </summary>
        internal static string strServerAdministrator {
            get {
                return ResourceManager.GetString("strServerAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار.
        /// </summary>
        internal static string strWarningTitle {
            get {
                return ResourceManager.GetString("strWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده اطلاعات.
        /// </summary>
        internal static string tsBrowse {
            get {
                return ResourceManager.GetString("tsBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ويرايش اطلاعات.
        /// </summary>
        internal static string tsEdit {
            get {
                return ResourceManager.GetString("tsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود اطلاعات.
        /// </summary>
        internal static string tsInsert {
            get {
                return ResourceManager.GetString("tsInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعه.
        /// </summary>
        internal static string wdFriday {
            get {
                return ResourceManager.GetString("wdFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوشنبه.
        /// </summary>
        internal static string wdMonday {
            get {
                return ResourceManager.GetString("wdMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شنبه.
        /// </summary>
        internal static string wdSaturday {
            get {
                return ResourceManager.GetString("wdSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يکشنبه.
        /// </summary>
        internal static string wdSunday {
            get {
                return ResourceManager.GetString("wdSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنجشنبه.
        /// </summary>
        internal static string wdThursday {
            get {
                return ResourceManager.GetString("wdThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه شنبه.
        /// </summary>
        internal static string wdTuesday {
            get {
                return ResourceManager.GetString("wdTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارشنبه.
        /// </summary>
        internal static string wdWednesday {
            get {
                return ResourceManager.GetString("wdWednesday", resourceCulture);
            }
        }
    }
}
